### ISSUE TITLE
work in alternative shells

### ISSUE THREAD

**Issue by crick-ru** [lukas2511/letsencrypt.sh#116]
It would be very nice if the script will run in alternative shells. For example, in busybox ash.
Now it is not working.

**Comment by lukas2511** [comment]
This is related to #109.

I think it's best trying to get this script somewhat posix compliant as this way it should work in quite a lot of shells.

**Comment by lukas2511** [comment]
Initial zsh compatiblity was added in da2eeda97d04817b895a6c85e72d5c5d53e32241.

Will continue working on compatibility with some other shells.

I think busybox ash (as you suggest) would be a good next target so this script works on embedded systems with openwrt, angstrom, alpine, etc.

**Comment by lukas2511** [comment]
I just had a look at busybox ash and I don't think porting this script is worth it.
Ash really lacks a lot of features, which would require a ton of workarounds....

I'm closing this ticket now since there already is support for at least one other shell (zsh), and I guess it would work in some others too.
If there are (minor) issues with other shells there should be new tickets created instead of adding to this.

**Comment by bittorf** [comment]
i was testing the script under busybox.
i dont see too much problems fixing it for POSIX (so working in every shell):

e.g. these calls (there are a lot of)
```
csr64="$( <<<"${csr}" openssl req -outform DER | urlbase64)"
```
can be converted to:
```
csr64="$( echo "${csr}" | openssl req -outform DER | urlbase64)"
```

another thing are:
```
[[ var =~ (foo|bar)$ ]] || ...
```
which can be written as:
```
case "$var" in
  *foo|*bar);;
  *) ... ;;
esac
```
another things are arrays, e.g. ${deploy_args[@]} where we can make a small function
