### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TabTwo** [lukas2511/letsencrypt.sh#63]
Any plans to add a license to this project?

**Comment by lukas2511** [comment]
It kinda feels wrong to add a LICENSE to a simple bash script, also I can't decide on which one to use...

**Comment by xtaran** [comment]
It's anything else than simple. :-)

And for being undecided, http://choosealicense.com/ might help. :-) If you don't care at all, I recommend the WTFPL, the Do What The Fuck You Want Public License. The name is more or less also the license text. ;-)

Problem is that due to common laws, if you don't declare a license, basically no one is even allowed to copy that file. :-(

**Comment by lukas2511** [comment]
this one should be good enough
